

server:
  port: 8082

  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connected_cars
    username: root
    password: Vedaannoji@07
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: vehicle-service
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
